### ISSUE TITLE
Not working when piped on macOS

### ISSUE THREAD

**Issue by aichholzer** [sindresorhus/term-size#1]
I had a similar idea, to read the columns using `tput 'cols'` for that matter, but still, the child process, does not have any knowledge of the parent window width, hence it does not quite work, it cannot be used to reliably get the window width, as you can see below.

![screen shot 2016-09-11 at 11 13 01](https://cloud.githubusercontent.com/assets/1402711/18414945/34bf960e-7811-11e6-877f-fd69c5dce747.png)
Looking at the above, the tests should not have passed. Sizes are different.

**Comment by sindresorhus** [comment]
That's really weird. It works fine for me. What macOS version are you on? Can you check which code path it hits in the module when running the `child size` test? Especially what the result of the `resize` command is?

On both Terminal and iTerm:

```
~/dev/term-size master 33s
❯ npm test

> term-size@0.1.0 test /Users/sindresorhus/dev/term-size
> xo && ava

main size: { columns: 143, rows: 24 }
child size: { columns: 143, rows: 24 }

   2 passed
```

I'm aware `tput` doesn't work when all file descriptors are redirected. That's why it tries `resize` first, which seems to work fine then, at least on my system.

**Comment by kevva** [comment]
```
$ npm test

> term-size@0.1.0 test /Users/kevva/.forks/term-size
> xo && ava

main size: { columns: 211, rows: 19 }
child size: { columns: 80, rows: 24 }

   2 passed
```

I don't have `resize` so it tries to use `tput`. I suspect that's the case for @aichholzer too.

**Comment by aichholzer** [comment]
Yes, I don't have `resize`, hence the issue.

**Comment by aichholzer** [comment]
I am currently writing (and testing) an alternative to `resize` which should do the trick, universally. In the meantime, perhaps it would be an idea to mention that this module does not effectively work as one might expect it to.
